parameters:
#    arii_core.example.class: Arii\CoreBundle\Example
      
services:
#    arii_core.example:
#        class: %arii_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services: 
    arii_core.log:
        class: Arii\ToolsBundle\Service\AriiLog
        arguments: [ "@doctrine.orm.default_entity_manager","@arii_core.session" ]

    arii_core.message:
        class: Arii\ToolsBundle\Service\AriiMessage
        arguments: [ "@doctrine.orm.default_entity_manager" ]

    arii_core.tools:
        class: Arii\ToolsBundle\Service\AriiTools
        arguments: [ "@arii_core.session", %workspace% ]
        
    arii_core.files:
        class: Arii\ToolsBundle\Service\AriiFiles
        arguments: [ "@arii_core.session", %workspace% ]

    arii_core.cron:
        class: Arii\ToolsBundle\Service\AriiCron
        arguments: [ "@arii_core.session" ]
      