parameters:
#    arii_mft.example.class: Arii\MFTBundle\Example

services:
#    arii_mft.example:
#        class: %arii_mft.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
