parameters:
#    arii_config.example.class: Arii\ConfigBundle\Example

services:
#    arii_config.example:
#        class: %arii_config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
