arii_homepage:
    pattern:  /
    defaults: {_controller: AriiCoreBundle:Default:index }

arii_home:
    pattern:  /home/{_locale}
    defaults: { _controller: AriiCoreBundle:Default:index }
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Core Bundle
# ----------------------------------------
arii_core:
    resource: "@AriiCoreBundle/Resources/config/routing.yml"
    prefix:   /home/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# JID 
# ----------------------------------------
arii_jid:
    resource: "@AriiJIDBundle/Resources/config/routing.yml"
    prefix:   /jid/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 
        
arii_jid_public:
    resource: "@AriiJIDBundle/Resources/config/routing_public.yml"
    prefix:   /public
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_jid_nagios:
    resource: "@AriiJIDBundle/Resources/config/routing_nagios.yml"
    prefix:   /nagios
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp


# ========================================
# DS 
# ----------------------------------------
arii_ds:
    resource: "@AriiDSBundle/Resources/config/routing.yml"
    prefix:   /ds/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# JOC
# ----------------------------------------
arii_JOC:
    resource: "@AriiJOCBundle/Resources/config/routing.yml"
    prefix:   /joc/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Graphviz
# ----------------------------------------
arii_GVZ:
    resource: "@AriiGraphvizBundle/Resources/config/routing.yml"
    prefix:   /gvz/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Report
# ----------------------------------------
arii_Report:
    resource: "@AriiReportBundle/Resources/config/routing.yml"
    prefix:   /report/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Admin 
# ----------------------------------------
arii_Admin:
    resource: "@AriiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# User Bundle
# ----------------------------------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

