<?php

namespace Arii\FocusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemoteSchedulersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteSchedulersRepository extends EntityRepository
{
}
