<?php

namespace Arii\FocusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * state_tasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends EntityRepository
{
}
