parameters:
#    arii_report.example.class: Arii\ReportBundle\Example

services:
#    arii_report.example:
#        class: %arii_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
