services:
#    arii_doc.example:
#        class: Arii\DOCBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arii_doc.doc:
        class: Arii\DOCBundle\Service\AriiDoc
        arguments: ["@request_stack"]
